runner:
  mypy:
    name: reviewdog/mypy
    cmd: mypy --strict --show-column-numbers -p varats
    errorformat:
      - "%f:%l:%c: %m"
    level: error

  pylint:
    cmd: pylint varats*
    errorformat:
      - "%f:%l:%c: %t%n: %m"
