runner:
  mypy:
    name: mypy
    cmd: mypy --strict --show-column-numbers -p varats
    errorformat:
      - "%f:%l:%c: %m"
    level: error

  ruff:
    name: ruff
    cmd: ruff check --output-format=rdjson
    format: rdjson
