"""Project file for TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject."""
import typing as tp

from benchbuild.project import Project
from benchbuild.utils.cmd import cmake, git, make
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.run import run
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.paper.paper_config import project_filter_generator
from varats.settings import bb_cfg
from varats.utils.project_util import (
    ProjectBinaryWrapper,
    get_all_revisions_between,
    wrap_paths_to_binaries,
)


@with_git(
    "https://github.com/se-passau/vara-test-repos",
    refspec="HEAD",
    shallow_clone=False,
    version_filter=project_filter_generator(
        "TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject"
    )
)
class TwoLibsOneProjectInteractionDiscreteLibsSingleProject(Project):
    """Class to analyse interactions between two discrete libraries and one
    project."""

    NAME = 'TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject'
    GROUP = 'cpp_projects'
    DOMAIN = 'analysis'
    VERSION = 'HEAD'

    SRC_FILE = NAME + "-{0}".format(VERSION)

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries(["elementalist"])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Contains instructions on how to build the project."""
        self.download()

        # cmake as build system
        with local.cwd(self.SRC_FILE):
            version_id = git("rev-parse", "HEAD").strip()
            cmake_revisions = get_all_revisions_between(
                "1cc6a93677f9a9825d3bbe20f1201e6652ba4a7d", "master"
            )

        if version_id in cmake_revisions:
            self.__compile_cmake()
        else:
            self.__compile_make()

    def __compile_cmake(self) -> None:
        clang = cc(self)
        with local.cwd(self.SRC_FILE):
            with local.env(CC=str(clang)):
                cmake("-G", "Unix Makefiles", ".")
            run(make["-j", get_number_of_jobs(bb_cfg())])

    def __compile_make(self) -> None:
        clang = cc(self)
        with local.cwd(self.SRC_FILE):
            with local.env(CC=str(clang)):
                run(make["-j", get_number_of_jobs(bb_cfg())])
