# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SingleCommitFilterProperties.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SingleCommitFilterProperties(object):

    def setupUi(self, SingleCommitFilterProperties):
        SingleCommitFilterProperties.setObjectName(
            "SingleCommitFilterProperties"
        )
        SingleCommitFilterProperties.resize(397, 51)
        self.verticalLayout = QtWidgets.QVBoxLayout(
            SingleCommitFilterProperties
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(SingleCommitFilterProperties)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.uiCommitHash = QtWidgets.QLineEdit(SingleCommitFilterProperties)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.uiCommitHash.setFont(font)
        self.uiCommitHash.setObjectName("uiCommitHash")
        self.horizontalLayout.addWidget(self.uiCommitHash)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SingleCommitFilterProperties)
        QtCore.QMetaObject.connectSlotsByName(SingleCommitFilterProperties)

    def retranslateUi(self, SingleCommitFilterProperties):
        _translate = QtCore.QCoreApplication.translate
        SingleCommitFilterProperties.setWindowTitle(
            _translate("SingleCommitFilterProperties", "Form")
        )
        self.label.setText(_translate("SingleCommitFilterProperties", "Commit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SingleCommitFilterProperties = QtWidgets.QWidget()
    ui = Ui_SingleCommitFilterProperties()
    ui.setupUi(SingleCommitFilterProperties)
    SingleCommitFilterProperties.show()
    sys.exit(app.exec_())
