name: 'Dependencies Template'
description: 'Install all system and python dependencies'

runs:
  using: "composite"
  steps:
    - name: Install system dependencies for CI
      run: |
         sudo apt-get install time git libgit2-dev ninja-build libyaml-dev libgraphviz-dev
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e ./varats-core
        pip install -e ./varats
        pip install -r requirements.txt
        pip install codecov
        pip install pytest-cov
        pip install coverage
        pip install mypy
        pip install tox
      shell: bash
