#!/bin/bash

pyuic5 -x MainWindow.ui -o ../varats/gui/ui_MainWindow.py
pyuic5 -x ExampleView.ui -o ../varats/gui/views/ui_ExampleView.py
pyuic5 -x CR-BarView.ui -o ../varats/gui/views/ui_CRBarView.py
