"""
Base plot module.
"""

import abc


class Plot():
    """
    An abstract base class for all plots generated by VaRA-TS
    """

    def __init__(self, name):
        self.__name = name
        self.__style = "classic"

    @property
    def name(self) -> str:
        """
        Name of the current plot.
        """
        return self.__name

    @property
    def style(self) -> str:
        """
        Current plot style
        """
        return self.__style

    @style.setter
    def style(self, new_style):
        self.__style = new_style

    @abc.abstractmethod
    def plot(self):
        """Plot the current plot to a file"""

    @abc.abstractmethod
    def show(self):
        """Show the current plot"""

    @abc.abstractmethod
    def save(self, filetype='svg'):
        """Save the current plot to a file"""
