"""Project file for openvpn."""
import typing as tp

from benchbuild.project import Project
from benchbuild.utils.cmd import ninja, cmake, git
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.run import run
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.data.provider.cve.cve_provider import CVEProviderHook
from varats.paper.paper_config import project_filter_generator
from varats.settings import bb_cfg
from varats.utils.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)


@with_git(
    "https://github.com/open-quantum-safe/liboqs.git",
    refspec="HEAD",
    version_filter=project_filter_generator("liboqs"),
    shallow_clone=False
)
class Liboqs(Project, CVEProviderHook):  # type: ignore
    """C library for quantum-safe cryptography (fetched by Git)"""

    NAME = 'liboqs'
    GROUP = 'c_projects'
    DOMAIN = 'security'
    VERSION = 'HEAD'

    SRC_FILE = NAME + "-{0}".format(VERSION)

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries(["build/liboqs"])

    def run_tests(self, runner: run) -> None:
        pass

    def compile(self) -> None:
        self.download()

        clang = cc(self)
        build_folder = local.path(self.SRC_FILE + "/" + "build")
        build_folder.mkdir()
        with local.cwd(build_folder):
            with local.env(CC=str(clang)):
                run(cmake["-G", "Ninja", ".."])
            run(ninja)

    @classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("openquantumsafe", "liboqs")]
