"""Project file for libssh."""
import typing as tp

import benchbuild as bb
from benchbuild.utils.cmd import make, cmake, mkdir
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.data.provider.cve.cve_provider import CVEProviderHook
from varats.paper.paper_config import project_filter_generator
from varats.settings import bb_cfg
from varats.utils.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)


class Libssh(bb.Project, CVEProviderHook):  # type: ignore
    """
    SSH library.

    (fetched by Git)
    """

    NAME = 'libssh'
    GROUP = 'c_projects'
    DOMAIN = 'library'

    SOURCE = [
        bb.source.Git(
            remote="https://github.com/libssh/libssh-mirror.git",
            local="libssh",
            refspec="HEAD",
            limit=None,
            shallow=False,
            version_filter=project_filter_generator("libssh")
        )
    ]

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries(['build/lib/libssh.so'])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        libssh_source = bb.path(self.source_of(self.primary_source))

        compiler = bb.compiler.cc(self)
        mkdir(libssh_source / "build")
        with local.cwd(libssh_source / "build"):
            with local.env(CC=str(compiler)):
                bb.watch(cmake)("-G", "Unix Makefiles", "..")

            bb.watch(make)("-j", get_number_of_jobs(bb_cfg()))

    @classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("Libssh", "Libssh")]
