"""
Project file for opus.
"""
import typing as tp
from pathlib import Path

from benchbuild.project import Project
from benchbuild.settings import CFG as BB_CFG
from benchbuild.utils.cmd import make
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.run import run

from plumbum import local

from varats.paper.paper_config import project_filter_generator
from varats.utils.project_util import wrap_paths_to_binaries


@with_git("https://github.com/xiph/opus.git",
          refspec="HEAD",
          version_filter=project_filter_generator("opus"))
class Opus(Project):  # type: ignore
    """
    Opus is a codec for interactive speech and audio transmission
    over the Internet.
    """

    NAME = 'opus'
    GROUP = 'c_projects'
    DOMAIN = 'codec'
    VERSION = 'HEAD'

    SRC_FILE = NAME + "-{0}".format(VERSION)

    @property
    def binaries(self) -> tp.List[Path]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries([".libs/opus_demo"])

    def run_tests(self, runner: run) -> None:
        pass

    def compile(self) -> None:
        self.download()

        self.cflags += ["-fPIC"]

        clang = cc(self)
        with local.cwd(self.SRC_FILE):
            with local.env(CC=str(clang)):
                run(local["./autogen.sh"])
                run(local["./configure"])
            run(make["-j", int(BB_CFG["jobs"])])

    def get_cve_product_info(self) -> tp.List[tp.Tuple[str, str]]:
        return [("opus-codec", "opus")]
