"""
Project file for qemu.
"""
import typing as tp
from pathlib import Path

from benchbuild.settings import CFG
from benchbuild.utils.compiler import cc, cxx
from benchbuild.utils.run import run
from benchbuild.project import Project
from benchbuild.utils.cmd import make, cmake, git
from benchbuild.utils.download import with_git

from plumbum import local

from varats.paper.paper_config import project_filter_generator
from varats.utils.project_util import (get_all_revisions_between,
                                       wrap_paths_to_binaries, block_revisions,
                                       BlockedRevisionRange, BugAndFixPair,
                                       BlockedRevision)


@with_git("https://github.com/qemu/qemu.git",
          refspec="HEAD",
          shallow_clone=False,
          version_filter=project_filter_generator("qemu"))
class Qemu(Project):  # type: ignore
    """ Programming language qemu"""

    NAME = 'qemu'
    GROUP = 'c_projects'
    DOMAIN = 'Hardware emulator'
    VERSION = 'HEAD'

    SRC_FILE = NAME + "-{0}".format(VERSION)

    @property
    def binaries(self) -> tp.List[Path]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries(
            ["build/x86_64-softmmu/qemu-system-x86_64"])

    def run_tests(self, runner: run) -> None:
        pass

    def compile(self) -> None:
        self.download()

        self.cflags += ['-Wno-tautological-type-limit-compare']

        c_compiler = cc(self)
        cxx_compiler = cxx(self)
        build_folder = local.path(self.SRC_FILE + "/" + "build")
        build_folder.mkdir()

        with local.cwd(build_folder):
            with local.env(CC=str(c_compiler), CXX=str(cxx_compiler)):
                run(local["../configure"]
                    ["--disable-debug-info", "--target-list=x86_64-softmmu"])
                run(make["-j", int(CFG["jobs"])])
