"""Reports for LLVM coverage generated using `llvm-cov` and `llvm-profdata`."""
import json
import typing as tp
from dataclasses import dataclass
from pathlib import Path

from varats.experiment.workload_util import WorkloadSpecificReportAggregate
from varats.report.report import BaseReport


@dataclass
class CodeRegion:
    """Class representing a code region in the coverage report."""

    def __init__(self, start: int, end: int) -> None:
        self.__start = start
        self.__end = end

    @property
    def start(self) -> int:
        """Return the start of the code region."""
        return self.__start

    @property
    def end(self) -> int:
        """Return the end of the code region."""
        return self.__end

    def __contains__(self, line: int) -> bool:
        """Check if the given line is in the code region."""
        return self.__start <= line < self.__end

    def __and__(self, other: "CodeRegion") -> "CodeRegion":
        """Returns the overlap of two code regions if it exists."""
        if self.contains(other.start) or self.contains(other.end):
            return CodeRegion(
                max(self.start, other.start), min(self.end, other.end)
            )

        return CodeRegion(1, 0)  # Empty region

    def __or__(self, other: "CodeRegion") -> "CodeRegion":
        """Returns the union of two code regions if it exists."""
        if self.contains(other.start) or self.contains(other.end):
            return CodeRegion(
                min(self.start, other.start), max(self.end, other.end)
            )

        return CodeRegion(1, 0)

    # Specializations for JSON serialization
    @staticmethod
    def to_json(obj: "CodeRegion") -> tp.Dict[str, tp.Any]:
        """Convert CodeRegion to JSON serializable format."""
        if not isinstance(obj, CodeRegion):
            raise TypeError(f"Cannot serialize object of type: {type(obj)}")
        return {"start": obj.start, "end": obj.end}

    @staticmethod
    def from_json(data: tp.Dict[str, tp.Any]) -> "CodeRegion":
        """Convert JSON data back to CodeRegion."""
        if not ("start" in data and "end" in data):
            raise ValueError("Invalid JSON data for CodeRegion")
        return CodeRegion(data["start"], data["end"])


class LLVMCoverageReport(BaseReport, shorthand="LCOV", file_type="json"):
    """
    LLVM coverage report.

    Already aggregates coverages on a line basis per source file.
    """

    NAME = "LLVM_Coverage_Report"
    DESCRIPTION = "LLVM coverage report"

    def __init__(self, path: Path) -> None:
        super().__init__(path)
        self.coverage_data_lines = {}
        self.coverage_data_functions = {}
        with open(path, "r") as file:
            data = json.load(file)

        # Convert tuples to CodeRegion objects
        for file, regions in data.items():
            self.coverage_data_lines[file.strip(":")] = [
                CodeRegion(r["start"], r["end"]) for r in regions["lines"]
            ]
            self.coverage_data_functions[file.strip(":")] = regions["functions"]

    def is_covered(self, filename: str, line: int) -> bool:
        if filename not in self.coverage_data_lines:
            return False

        return any(
            line in region for region in self.coverage_data_lines[filename]
        )


class MWLCoverageReport(
    WorkloadSpecificReportAggregate[LLVMCoverageReport],
    shorthand="MLCOV",
    file_type="zip"
):
    """
    Multi-workload LLVM coverage report.

    This report aggregates multiple `LLVMCoverageReport`s for different
    workloads into a single report.
    """

    def __init__(self, path: Path) -> None:
        super().__init__(path, LLVMCoverageReport)


class LLVMProfDataReport(BaseReport, shorthand="LPD", file_type="profdata"):
    """
    Report for raw LLVM profiles.

    This report is generated by `llvm-profdata` and contains merged profile
    data.
    """

    NAME = "LLVM_ProfData"
    DESCRIPTION = "LLVM raw profile data report"

    def __init__(self, path: Path) -> None:
        super().__init__(path)
