"""Project file for TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject."""
import typing as tp

import benchbuild as bb
from benchbuild.utils.cmd import cmake, make
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.paper.paper_config import project_filter_generator
from varats.utils.project_util import (
    ProjectBinaryWrapper,
    wrap_paths_to_binaries,
)
from varats.utils.settings import bb_cfg


class TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject(
    bb.Project
):  # type: ignore
    """Class to analyse interactions between two discrete libraries and one
    project."""

    NAME = 'TwoLibsOneProjectInteraction_DiscreteLibs_SingleProject'
    GROUP = 'cpp_projects'
    DOMAIN = 'library-testproject'

    SOURCE = [
        bb.source.Git(
            remote="https://github.com/se-passau/vara-test-repos",
            local="vara-test-repos",
            refspec="HEAD",
            limit=None,
            shallow=False,
            version_filter=project_filter_generator("vara-test-repos")
        )
    ]

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries([
            "Elementalist/test_prog/elementalist"
            "/elementalist"
        ])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Contains instructions on how to build the project."""

        version_source = local.path(self.source_of_primary)
        clang = bb.compiler.cc(self)
        with local.cwd(version_source):
            with local.env(CC=str(clang)):
                bb.watch(cmake)("-G", "Unix Makefiles", ".")
            bb.watch(make)("-j", get_number_of_jobs(bb_cfg()))
