"""
VaRA-TS project abstraction.

This module defines the main project abstractions for VaRA-TS that extend the
benchbuild interface with tool suite specific functions.
"""
import typing as tp
from abc import abstractmethod
from pathlib import Path
from typing import Protocol, runtime_checkable

from benchbuild.project import Project

from varats.project.project_domain import ProjectDomains
from varats.utils.git_util import ShortCommitHash

if tp.TYPE_CHECKING:
    # pylint: disable=W0611
    from varats.project.project_util import ProjectBinaryWrapper


class VProject(Project):  # type: ignore
    """VaRA-TS project abstraction, extending the interface which is required
    from benchbuild."""

    DOMAIN: ProjectDomains

    @property
    def binaries(self) -> tp.List['ProjectBinaryWrapper']:
        """Return a list of binaries generated by the project."""
        return self.binaries_for_revision(
            ShortCommitHash(self.version_of_primary)
        )

    @staticmethod
    @abstractmethod
    def binaries_for_revision(
        revision: ShortCommitHash  # pylint: disable=W0613
    ) -> tp.List['ProjectBinaryWrapper']:
        """
        Return a list of binaries generated by the project, for the given
        revision.

        Args:
            revision: to determine the binaries for

        Returns:
            list of project binaries
        """


@runtime_checkable
class SupportsTesting(Protocol):
    """Interface for projects that support testing."""

    def prepare_test_environment(self) -> None:
        """
        Prepare the test environment for this project.

        After running this method, the test environment should be prepared such
        that tests are discoverable for the get_test_names() method. This does
        not necessarily mean that the tests are built yet.
        """
        ...

    def build_tests(self) -> None:
        """
        Build the tests for this project.

        Should be called after prepare_test_environment() to build the tests.
        Once this method is called, the tests should be built and ready to run.
        """
        ...

    def run_testsuite(
        self,
        test_report_path: tp.Optional[Path] = None,
        tests_to_run: tp.Optional[tp.Iterable[str]] = None
    ) -> bool:
        """
        Run the test suite for this project.

        Args:
            test_report_path: Path to the test report file.
            tests_to_run: List of test cases to run. If None, all tests will be run.

        Returns:
            True is all tests passed, False otherwise.
        """
        ...

    def get_test_names(self) -> tp.Iterable[str]:
        """
        Returns a list of tests that can be run for this project in the current
        revision and configuration. Requires that prepare_test_environment() was
        called before.

        Returns:
             A list of tests available for this project.
        """
        ...
