"""Project file for FreeBSD."""
import typing as tp
import benchbuild as bb
from benchbuild.project import Project
from benchbuild.utils.cmd import make
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
#from benchbuild.utils.run import run
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.provider.cve.cve_provider import CVEProviderHook
from varats.paper_mgmt.paper_config import project_filter_generator
from varats.project.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)


class FreeBSD(Project, CVEProviderHook):  # type: ignore
    """The FreeBSD Project (fetched by Git)"""

    NAME = 'FreeBSD'
    GROUP = 'c_projects'
    DOMAIN = 'OS'
    VERSION = 'HEAD'

    # SRC_FILE = NAME + "-{0}".format(VERSION)
    SOURCE = bb.source.Git(
        remote="https://github.com/freebsd/freebsd.git",
        refspec="HEAD",
        version_filter=project_filter_generator("FreeBSD"),
        local="FreeBSD"
    )

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        # TODO: What to input here? (it is an operating system)
        return wrap_paths_to_binaries(["FreeBSD"])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        # self.download()

        path = local.path(self.source_of(self.primary_source))

        clang = cc(self)
        with local.cwd(path):
            with local.env(CC=str(clang)):
                # Hope, the kernel is enough to show OpenSSL behaviour; 'make universe' takes 167 GiB space...
                # run(make["buildkernel", "-j", get_number_of_jobs(bb_cfg())])
                bb.watch(make)("buildkernel", "-j", get_number_of_jobs(bb_cfg()))

    @ classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("FreeBSD", "FreeBSD")]
