"""Project file for liboqs."""
import typing as tp

import benchbuild as bb
from benchbuild.project import Project
from benchbuild.utils.cmd import make, source
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.provider.cve.cve_provider import CVEProviderHook
from varats.paper_mgmt.paper_config import project_filter_generator

from varats.project.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)


class Liboqs(Project, CVEProviderHook):  # type: ignore
    """C library for quantum-safe cryptography (fetched by Git)"""

    NAME = 'liboqs'
    GROUP = 'c_projects'
    DOMAIN = 'security'
    VERSION = 'HEAD'

    #SRC_FILE = NAME + "-{0}".format(VERSION)
    SOURCE = bb.source.Git(
        remote="https://github.com/open-quantum-safe/liboqs.git",
        refspec="HEAD",
        version_filter=project_filter_generator("liboqs"),
        shallow=False,
        local="liboqs"
    )

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries(["build/liboqs"])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        # self.download()

        path = local.path(self.source_of(self.primary_source))

        clang = bb.compiler.cc(self)
        build_folder = local.path(path + "/" + "build")
        build_folder.mkdir()
        with local.cwd(build_folder):
            with local.env(CC=str(clang)):
                #run(cmake["-G", "Ninja", ".."])
                bb.watch(cmake)("-G", "Ninja", "..")
            # run(ninja)
            bb.watch(ninja)()

    @classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("openquantumsafe", "liboqs")]
