"""Project file for moloch."""
import typing as tp

import benchbuild as bb
from benchbuild.project import Project
from benchbuild.utils.cmd import make, source
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.provider.cve.cve_provider import CVEProviderHook
from varats.paper_mgmt.paper_config import project_filter_generator

from varats.project.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)

class Moloch(Project, CVEProviderHook):  # type: ignore
    """An open source, large scale, full packet capturing, indexing, and database system (fetched by Git)"""

    NAME = 'moloch'
    GROUP = 'c_projects'
    DOMAIN = 'security'
    VERSION = 'HEAD'

    SOURCE = bb.source.Git(
        remote="https://github.com/aol/moloch.git",
        refspec="HEAD",
        version_filter=project_filter_generator("moloch"),
        local="moloch"
    )

    #SRC_FILE = NAME + "-{0}".format(VERSION)

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        # TODO
        return wrap_paths_to_binaries(["moloch"])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        moloch_path = local.path(self.source_of(self.primary_source))
        clang = bb.compiler.cc(self)
        with local.cwd(moloch_path):
            with local.env(CC=str(clang)):
                #run(local["./easybutton-build.sh", "--install"])
                bb.watch(local["./easybutton-build.sh"])("--install")
                #run(make["config", "-j", get_number_of_jobs(bb_cfg())])
                bb.watch(make)("config", "-j", get_number_of_jobs(bb_cfg()))

    @classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("aol", "moloch")]
