"""Project file for OpenSC."""
import typing as tp

import benchbuild as bb
from benchbuild.project import Project
from benchbuild.utils.cmd import make
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.run import run
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.data.provider.cve.cve_provider import CVEProviderHook
from varats.paper.paper_config import project_filter_generator
from varats.settings import bb_cfg
from varats.utils.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)


class OpenSC(Project, CVEProviderHook):  # type: ignore
    """Open source smart card tools and middleware (fetched by Git)"""

    NAME = 'OpenSC'
    GROUP = 'c_projects'
    DOMAIN = 'security'
    VERSION = 'HEAD'

    #SRC_FILE = NAME + "-{0}".format(VERSION)
    SOURCE = bb.source.Git(
        "https://github.com/OpenSC/OpenSC.git",
        refspec="HEAD",
        version_filter=project_filter_generator("OpenSC")
    )

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries(["OpenSC"])

    def run_tests(self, runner: run) -> None:
        pass

    def compile(self) -> None:
        # self.download()
        path = local.path(self.source_of(self.primary_source))
        # TODO: install dependencies:
        # sudo apt-get install pcscd libccid libpcsclite-dev libssl-dev libreadline-dev autoconf automake build-essential docbook-xsl xsltproc libtool pkg-config
        # sudo apt-get install zlib1g-dev
        clang = bb.compiler.cc(self)
        with local.cwd(path):
            with local.env(CC=str(clang)):
                # run(local["./bootstrap"])
                bb.watch(local["./bootstrap"])()
                # run(local["./configure"])
                bb.watch(local["./configure"])()
                #run(make["-j", get_number_of_jobs(bb_cfg())])
                bb.watch(make)("-j", get_number_of_jobs(bb_cfg()))

    @classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("OpenSC", "OpenSC")]
