"""Project file for zcoin."""
import typing as tp
import benchbuild as bb
from benchbuild.project import Project
from benchbuild.utils.cmd import make
from benchbuild.utils.compiler import cc
from benchbuild.utils.download import with_git
from benchbuild.utils.run import run
from benchbuild.utils.settings import get_number_of_jobs
from plumbum import local

from varats.data.provider.cve.cve_provider import CVEProviderHook
from varats.paper.paper_config import project_filter_generator
from varats.settings import bb_cfg
from varats.utils.project_util import (
    wrap_paths_to_binaries,
    ProjectBinaryWrapper,
)


class ZCoin(Project, CVEProviderHook):  # type: ignore
    """The privacy-focused cryptocurrency (fetched by Git)"""

    NAME = 'zcoin'
    GROUP = 'c_projects'
    DOMAIN = 'cryptocurrency'
    VERSION = 'HEAD'

    #SRC_FILE = NAME + "-{0}".format(VERSION)
    SOURCE = bb.source.Git(
        "https://github.com/zcoinofficial/zcoin.git",
        refspec="HEAD",
        version_filter=project_filter_generator("zcoin")
    )

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        # TODO
        return wrap_paths_to_binaries(["zcoin"])

    def run_tests(self, runner: run) -> None:
        pass

    def compile(self) -> None:
        # self.download()
        path = local.path(self.source_of(self.primary_source))
        # TODO: install dependencies:
        # sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libgmp-dev cmake
        # sudo apt-get install software-properties-common
        # sudo add-apt-repository ppa:bitcoin/bitcoin
        # sudo apt-get update
        # sudo apt-get install libdb4.8-dev libdb4.8++-dev
        clang = bb.compiler.cc(self)
        with local.cwd(path):
            with local.env(CC=str(clang)):
                # run(local["./autogen.sh"])
                bb.watch(local["./autogen.sh"])()
                #run(local["./configure", "--without-gui"])
                bb.watch(local["./configure"])("--without-gui")
                #run(make["-j", get_number_of_jobs(bb_cfg())])
                bb.watch(make)("-j", get_number_of_jobs(bb_cfg()))

    @classmethod
    def get_cve_product_info(cls) -> tp.List[tp.Tuple[str, str]]:
        return [("zcoinofficial", "zcoin")]
