"""Project to run tests from the micro-benchmark Test-Suite."""
import typing as tp
from pathlib import Path

import benchbuild as bb
from plumbum import local

from varats.project.project_util import (
    ProjectBinaryWrapper,
    wrap_paths_to_binaries,
    BinaryType,
)


class SVFPointsToAnalysisBenchmark(bb.Project):  # type: ignore
    """
    SVFPointsToAnalysisBenchmark provides an easy way to execute the examples
    from the Test-Suite micro-benchmark suite for testing points to analyses.

    Which can be found at https://github.com/SVF-tools/Test-Suite.
    """

    NAME = 'SVFPointsToBench'
    GROUP = 'test_projects'
    DOMAIN = 'testing'

    SOURCE = [
        bb.source.Git(
            remote="https://github.com/SVF-tools/Test-Suite.git",
            local="svf-test-suite",
            refspec="HEAD",
            limit=1,  # None,
            shallow=False,
        )
    ]

    FILE_PATHS: tp.List[Path] = [
        # basic_c_tests
        Path("basic_c_tests/array-constIdx.c"),
        Path("basic_c_tests/array-varIdx2.c"),
        Path("basic_c_tests/array-varIdx.c"),
        Path("basic_c_tests/branch-call.c"),
        Path("basic_c_tests/branch-intra.c"),
        Path("basic_c_tests/CI-funptr.c"),
        Path("basic_c_tests/CI-global.c"),
        Path("basic_c_tests/CI-local.c"),
        Path("basic_c_tests/constraint-cycle-copy.c"),
        Path("basic_c_tests/constraint-cycle-field.c"),
        Path("basic_c_tests/constraint-cycle-pwc.c"),
        Path("basic_c_tests/field-ptr-arith-constIdx.c"),
        Path("basic_c_tests/field-ptr-arith-varIdx.c"),
        Path("basic_c_tests/funptr-global.c"),
        Path("basic_c_tests/funptr-nested-call.c"),
        Path("basic_c_tests/funptr-simple.c"),
        Path("basic_c_tests/funptr-struct.c"),
        Path("basic_c_tests/global-array.c"),
        Path("basic_c_tests/global-call-noparam.c"),
        Path("basic_c_tests/global-call-struct.c"),
        Path("basic_c_tests/global-call-twoparms.c"),
        Path("basic_c_tests/global-const-struct.c"),
        Path("basic_c_tests/global-funptr.c"),
        Path("basic_c_tests/global-initializer.c"),
        Path("basic_c_tests/global-nested-calls.c"),
        Path("basic_c_tests/global-simple.c"),
        Path("basic_c_tests/heap-indirect.c"),
        Path("basic_c_tests/heap-linkedlist.c"),
        Path("basic_c_tests/heap-wrapper.c"),
        Path("basic_c_tests/int2pointer.c"),
        Path("basic_c_tests/mesa.c"),
        Path("basic_c_tests/ptr-dereference1.c"),
        Path("basic_c_tests/ptr-dereference2.c"),
        Path("basic_c_tests/ptr-dereference3.c"),
        Path("basic_c_tests/spec-equake.c"),
        Path("basic_c_tests/spec-gap.c"),
        Path("basic_c_tests/spec-mesa.c"),
        Path("basic_c_tests/spec-parser.c"),
        Path("basic_c_tests/spec-vortex.c"),
        Path("basic_c_tests/struct-array.c"),
        Path("basic_c_tests/struct-assignment-direct.c"),
        Path("basic_c_tests/struct-assignment-indirect.c"),
        Path("basic_c_tests/struct-assignment-nested.c"),
        Path("basic_c_tests/struct-field-multi-dereference.c"),
        Path("basic_c_tests/struct-incompab-typecast.c"),
        Path("basic_c_tests/struct-incompab-typecast-nested.c"),
        Path("basic_c_tests/struct-instance-return.c"),
        Path("basic_c_tests/struct-nested-1-layer.c"),
        Path("basic_c_tests/struct-nested-2-layers.c"),
        Path("basic_c_tests/struct-nested-array1.c"),
        Path("basic_c_tests/struct-nested-array2.c"),
        Path("basic_c_tests/struct-nested-array3.c"),
        Path("basic_c_tests/struct-onefld.c"),
        Path("basic_c_tests/struct-simple.c"),
        Path("basic_c_tests/struct-twoflds.c"),

        # basic_cpp_tests
        Path("basic_cpp_tests/abstract.cpp"),
        Path("basic_cpp_tests/array-1.cpp"),
        Path("basic_cpp_tests/array-2.cpp"),
        Path("basic_cpp_tests/array-3.cpp"),
        Path("basic_cpp_tests/clean.sh"),
        Path("basic_cpp_tests/constructor-1.cpp"),
        Path("basic_cpp_tests/constructor-2.cpp"),
        Path("basic_cpp_tests/deque-1.cpp"),
        Path("basic_cpp_tests/deque-2.cpp"),
        Path("basic_cpp_tests/deque-3.cpp"),
        Path("basic_cpp_tests/deque-4.cpp"),
        Path("basic_cpp_tests/destructor-1.cpp"),
        Path("basic_cpp_tests/destructor-2.cpp"),
        Path("basic_cpp_tests/diamond-inheritance.cpp"),
        Path("basic_cpp_tests/dynamic_cast-1.cpp"),
        Path("basic_cpp_tests/forward_list-1.cpp"),
        Path("basic_cpp_tests/forward_list-2.cpp"),
        Path("basic_cpp_tests/forward_list-3.cpp"),
        Path("basic_cpp_tests/forward_list-4.cpp"),
        Path("basic_cpp_tests/func-ptr-in-class.cpp"),
        Path("basic_cpp_tests/global-obj-in-array.cpp"),
        Path("basic_cpp_tests/list-1.cpp"),
        Path("basic_cpp_tests/list-2.cpp"),
        Path("basic_cpp_tests/map-1.cpp"),
        Path("basic_cpp_tests/map-2.cpp"),
        Path("basic_cpp_tests/member-variable.cpp"),
        Path("basic_cpp_tests/pwc.cpp"),
        Path("basic_cpp_tests/queue-1.cpp"),
        Path("basic_cpp_tests/queue-2.cpp"),
        Path("basic_cpp_tests/set-1.cpp"),
        Path("basic_cpp_tests/set-2.cpp"),
        Path("basic_cpp_tests/single-inheritance-1.cpp"),
        Path("basic_cpp_tests/single-inheritance-2.cpp"),
        Path("basic_cpp_tests/single-inheritance-3.cpp"),
        Path("basic_cpp_tests/single-inheritance-4.cpp"),
        Path("basic_cpp_tests/stack-1.cpp"),
        Path("basic_cpp_tests/stack-2.cpp"),
        Path("basic_cpp_tests/unordered_map-1.cpp"),
        Path("basic_cpp_tests/unordered_map-2.cpp"),
        Path("basic_cpp_tests/unordered_set-1.cpp"),
        Path("basic_cpp_tests/variant-gep.cpp"),
        Path("basic_cpp_tests/vector-1.cpp"),
        Path("basic_cpp_tests/vector-2.cpp"),
        Path("basic_cpp_tests/vector-3.cpp"),
        Path("basic_cpp_tests/vector-4.cpp"),
        Path("basic_cpp_tests/virtual-call-simple.cpp"),
        Path("basic_cpp_tests/virtual-diamond-inheritance-2.cpp"),
        Path("basic_cpp_tests/virtual-inheritance-1.cpp"),
        Path("basic_cpp_tests/virtual-inheritance-2.cpp"),
        Path("basic_cpp_tests/virtual-inheritance-3.cpp"),

        # complex_test
        Path("complex_tests/cond-swap.c"),
        Path("complex_tests/instrument.sh"),
        Path("complex_tests/swap1.c"),
        Path("complex_tests/swap4.c"),
        Path("complex_tests/swap4-context1.c"),
        Path("complex_tests/swap4-context.c"),
        Path("complex_tests/swap4-contextindirect.c"),
        Path("complex_tests/swap-array.c"),
        Path("complex_tests/swap.c"),
        Path("complex_tests/swap-funcptr1.c"),
        Path("complex_tests/swap-funcptr2.c"),
        Path("complex_tests/swap-funcptr.c"),
        Path("complex_tests/swap-global1.c"),
        Path("complex_tests/swap-global2.c"),
        Path("complex_tests/swap-global.c"),
        Path("complex_tests/swap-heap1.c"),
        Path("complex_tests/swap-heap2.c"),
        Path("complex_tests/swap-heap3.c"),
        Path("complex_tests/swap-heap4.c"),
        Path("complex_tests/swap-heap.c"),
        Path("complex_tests/swap-indirect1.c"),
        Path("complex_tests/swap-indirect2.c"),
        Path("complex_tests/swap-indirect.c"),
        Path("complex_tests/swap-recursion.c"),
        Path("complex_tests/swap-struct1.c"),
        Path("complex_tests/swap-struct.c"),
        Path("complex_tests/swap-structindirect.c"),
        Path("complex_tests/test1.c"),
        Path("complex_tests/test1-path.c"),
        Path("complex_tests/test2.c"),
        Path("complex_tests/test2-path.c"),
        Path("complex_tests/test3.c"),
        Path("complex_tests/test3-path.c"),
        Path("complex_tests/test4.c"),
        Path("complex_tests/test5.c"),
        Path("complex_tests/test6.c"),
        Path("complex_tests/test8.c"),
        Path("complex_tests/test.c"),
        Path("complex_tests/test-clone1.c"),
        Path("complex_tests/test-clone.c"),
        Path("complex_tests/test-cond.c"),
        Path("complex_tests/test-globalstruct.c"),
        Path("complex_tests/test-indirect1.c"),
        Path("complex_tests/test-indirect.c"),
        Path("complex_tests/test-linklist1.c"),
        Path("complex_tests/test-linklist.c"),
        Path("complex_tests/test-path.c"),
        Path("complex_tests/test-recursive0.c"),
        Path("complex_tests/test-recursive1.c"),
        Path("complex_tests/test-recursive2.c"),
        Path("complex_tests/test-recursive.c"),
        Path("complex_tests/test-recursiveglobal1.c"),
        Path("complex_tests/test-recursiveglobal2.c"),
        Path("complex_tests/test-recursiveglobal.c"),

        # cs_tests
        Path("cs_tests/cs0.c"),
        Path("cs_tests/cs10.c"),
        Path("cs_tests/cs11.c"),
        Path("cs_tests/cs12.c"),
        Path("cs_tests/cs13.c"),
        Path("cs_tests/cs14.c"),
        Path("cs_tests/cs15.c"),
        Path("cs_tests/cs16.c"),
        Path("cs_tests/cs17.c"),
        Path("cs_tests/cs18.c"),
        Path("cs_tests/cs19.c"),
        Path("cs_tests/cs1.c"),
        Path("cs_tests/cs20.c"),
        Path("cs_tests/cs21.c"),
        Path("cs_tests/cs2.c"),
        Path("cs_tests/cs3.c"),
        Path("cs_tests/cs4.c"),
        Path("cs_tests/cs5.c"),
        Path("cs_tests/cs6.c"),
        Path("cs_tests/cs7.c"),
        Path("cs_tests/cs8.c"),
        Path("cs_tests/cs9.c"),
        Path("cs_tests/funcpoiner.c"),
        Path("cs_tests/recur0.c"),
        Path("cs_tests/recur10.c"),
        Path("cs_tests/recur2.c"),
        Path("cs_tests/recur3.c"),
        Path("cs_tests/recur4.c"),
        Path("cs_tests/recur5.c"),
        Path("cs_tests/recur6.c"),
        Path("cs_tests/recur7.c"),
        Path("cs_tests/recur8.c"),
        Path("cs_tests/recur9.c"),

        # fs_tests
        Path("fs_tests/array_alias_1.c"),
        Path("fs_tests/array_alias_2.c"),
        Path("fs_tests/array_alias_3.c"),
        Path("fs_tests/array_alias_4.c"),
        Path("fs_tests/array_alias_5.c"),
        Path("fs_tests/branch_1.c"),
        Path("fs_tests/branch_2.c"),
        Path("fs_tests/branch_3.c"),
        Path("fs_tests/function_pointer_2.c"),
        Path("fs_tests/function_pointer.c"),
        Path("fs_tests/global_1.c"),
        Path("fs_tests/global_2.c"),
        Path("fs_tests/global_3.c"),
        Path("fs_tests/global_4.c"),
        Path("fs_tests/global_5.c"),
        Path("fs_tests/pcycle1.c"),
        Path("fs_tests/pcycle2.c"),
        Path("fs_tests/return.c"),
        Path("fs_tests/simple_1.c"),
        Path("fs_tests/simple_2.c"),
        Path("fs_tests/simple_3.c"),
        Path("fs_tests/strong_update.c"),
        Path("fs_tests/struct_1.c"),
        Path("fs_tests/struct_2.c"),
        Path("fs_tests/test-su.c"),
        Path("fs_tests/tt.c"),

        # fstbhc_tests
        Path("fstbhc_tests/array1.c"),
        Path("fstbhc_tests/basic1.c"),
        Path("fstbhc_tests/constructor1.cpp"),
        Path("fstbhc_tests/field1.c"),
        Path("fstbhc_tests/field2.c"),
        Path("fstbhc_tests/field3.c"),
        Path("fstbhc_tests/loop.c"),
        Path("fstbhc_tests/static_first_field.cpp"),
        Path("fstbhc_tests/union.c"),
        Path("fstbhc_tests/virtual1.cpp"),
        Path("fstbhc_tests/virtual2.cpp"),
        Path("fstbhc_tests/virtual3.cpp"),
        Path("fstbhc_tests/xmalloc1.c"),
        Path("fstbhc_tests/xmalloc2.c"),
        Path("fstbhc_tests/xmalloc3.c"),

        # path_tests
        Path("path_tests/path10.c"),
        Path("path_tests/path11.c"),
        Path("path_tests/path12.c"),
        Path("path_tests/path13.c"),
        Path("path_tests/path14.c"),
        Path("path_tests/path15.c"),
        Path("path_tests/path16.c"),
        Path("path_tests/path17.c"),
        Path("path_tests/path18.c"),
        Path("path_tests/path19.c"),
        Path("path_tests/path1.c"),
        Path("path_tests/path20.c"),
        Path("path_tests/path21.c"),
        Path("path_tests/path22.c"),
        Path("path_tests/path2.c"),
        Path("path_tests/path3.c"),
        Path("path_tests/path4.c"),
        Path("path_tests/path5.c"),
        Path("path_tests/path6.c"),
        Path("path_tests/path7.c"),
        Path("path_tests/path8.c"),
        Path("path_tests/path9.c"),

        # mem_leak
        Path("mem_leak/malloc0.c"),
        Path("mem_leak/malloc10.c"),
        Path("mem_leak/malloc11.c"),
        Path("mem_leak/malloc12.c"),
        Path("mem_leak/malloc13.c"),
        Path("mem_leak/malloc14.c"),
        Path("mem_leak/malloc15.c"),
        Path("mem_leak/malloc16.c"),
        Path("mem_leak/malloc17.c"),
        Path("mem_leak/malloc18.c"),
        Path("mem_leak/malloc19.c"),
        Path("mem_leak/malloc1.c"),
        Path("mem_leak/malloc20.c"),
        Path("mem_leak/malloc21.c"),
        Path("mem_leak/malloc22.c"),
        Path("mem_leak/malloc23.c"),
        Path("mem_leak/malloc24.c"),
        Path("mem_leak/malloc25.c"),
        Path("mem_leak/malloc26.c"),
        Path("mem_leak/malloc27.c"),
        Path("mem_leak/malloc28.c"),
        Path("mem_leak/malloc29.c"),
        Path("mem_leak/malloc2.c"),
        Path("mem_leak/malloc30.c"),
        Path("mem_leak/malloc31.c"),
        Path("mem_leak/malloc32.c"),
        Path("mem_leak/malloc33.c"),
        Path("mem_leak/malloc34.c"),
        Path("mem_leak/malloc35.c"),
        Path("mem_leak/malloc36.c"),
        Path("mem_leak/malloc37.c"),
        Path("mem_leak/malloc38.c"),
        Path("mem_leak/malloc39.c"),
        Path("mem_leak/malloc3.c"),
        Path("mem_leak/malloc40.c"),
        Path("mem_leak/malloc41.c"),
        Path("mem_leak/malloc42.c"),
        Path("mem_leak/malloc43.c"),
        Path("mem_leak/malloc44.c"),
        Path("mem_leak/malloc45.c"),
        Path("mem_leak/malloc46.c"),
        Path("mem_leak/malloc47.c"),
        Path("mem_leak/malloc48.c"),
        Path("mem_leak/malloc49.c"),
        Path("mem_leak/malloc4.c"),
        Path("mem_leak/malloc50.c"),
        Path("mem_leak/malloc51.c"),
        Path("mem_leak/malloc52.c"),
        Path("mem_leak/malloc53.c"),
        Path("mem_leak/malloc54.c"),
        Path("mem_leak/malloc55.c"),
        Path("mem_leak/malloc56.c"),
        Path("mem_leak/malloc57.c"),
        Path("mem_leak/malloc58.c"),
        Path("mem_leak/malloc59.c"),
        Path("mem_leak/malloc5.c"),
        Path("mem_leak/malloc60.c"),
        Path("mem_leak/malloc61.c"),
        Path("mem_leak/malloc62.c"),
        Path("mem_leak/malloc63.c"),
        Path("mem_leak/malloc64.c"),
        Path("mem_leak/malloc6.c"),
        Path("mem_leak/malloc7.c"),
        Path("mem_leak/malloc8.c"),
        Path("mem_leak/malloc9.c"),
        Path("mem_leak/sp10.c"),
        Path("mem_leak/sp11.c"),
        Path("mem_leak/sp12a.c"),
        Path("mem_leak/sp12.c"),
        Path("mem_leak/sp13a.c"),
        Path("mem_leak/sp13.c"),
        Path("mem_leak/sp14a.c"),
        Path("mem_leak/sp14.c"),
        Path("mem_leak/sp15a.c"),
        Path("mem_leak/sp15.c"),
        Path("mem_leak/sp1a.c"),
        Path("mem_leak/sp1.c"),
        Path("mem_leak/sp22.c"),
        Path("mem_leak/sp2a.c"),
        Path("mem_leak/sp2.c"),
        Path("mem_leak/sp3a.c"),
        Path("mem_leak/sp3.c"),
        Path("mem_leak/sp41.c"),
        Path("mem_leak/sp4a.c"),
        Path("mem_leak/sp4.c"),
        Path("mem_leak/sp5a.c"),
        Path("mem_leak/sp5.c"),
        Path("mem_leak/sp6a.c"),
        Path("mem_leak/sp6.c"),
        Path("mem_leak/sp7.c"),
        Path("mem_leak/sp8.c"),
        Path("mem_leak/sp9.c"),

        # mta
        Path("mta/imprecise_cxt_indfork_1.c"),
        Path("mta/imprecise_cxt_indfork_2.c"),
        Path("mta/imprecise_cxt_indfork_3.c"),
        Path("mta/imprecise_cxt_join_4.c"),
        Path("mta/imprecise_cxt_join_5.c"),
        Path("mta/imprecise_cxt_loop_5.c"),
        Path("mta/imprecise_cxt_offspring_5.c"),
        Path("mta/imprecise_cxt_recur_2.c"),
        Path("mta/imprecise_cxt_recur_3.c"),
        Path("mta/imprecise_cxt_recur_5.c"),
        Path("mta/imprecise_cxt_recur_6.c"),
        Path("mta/imprecise_cxt_thdindex_10.c"),
        Path("mta/imprecise_cxt_thdindex_3.c"),
        Path("mta/imprecise_cxt_thdindex_4_1.c"),
        Path("mta/imprecise_cxt_thdindex_4_2.c"),
        Path("mta/imprecise_cxt_thdindex_8_2.c"),
        Path("mta/imprecise_cxt_thdindex_9.c"),
        Path("mta/mta_failed"),
        Path("mta/succ_cxt_branch_1.c"),
        Path("mta/succ_cxt_branch_2.c"),
        Path("mta/succ_cxt_branch_3.c"),
        Path("mta/succ_cxt_branch_4.c"),
        Path("mta/succ_cxt_branch_5.c"),
        Path("mta/succ_cxt_cand_1.c"),
        Path("mta/succ_cxt_cand_2.c"),
        Path("mta/succ_cxt_cand_3.c"),
        Path("mta/succ_cxt_join_1.c"),
        Path("mta/succ_cxt_join_2.c"),
        Path("mta/succ_cxt_join_3.c"),
        Path("mta/succ_cxt_loop_1.c"),
        Path("mta/succ_cxt_loop_2.c"),
        Path("mta/succ_cxt_loop_3.c"),
        Path("mta/succ_cxt_loop_6.c"),
        Path("mta/succ_cxt_loop_8.c"),
        Path("mta/succ_cxt_offspring_1.c"),
        Path("mta/succ_cxt_offspring_2.c"),
        Path("mta/succ_cxt_offspring_3.c"),
        Path("mta/succ_cxt_offspring_4.c"),
        Path("mta/succ_cxt_recur_4.c"),
        Path("mta/succ_cxt_recur_7.c"),
        Path("mta/succ_cxt_recur_index_1.c"),
        Path("mta/succ_cxt_sibling_1.c"),
        Path("mta/succ_cxt_sibling_2.c"),
        Path("mta/succ_cxt_sibling_3.c"),
        Path("mta/succ_cxt_sibling_4.c"),
        Path("mta/succ_cxt_sibling_5.c"),
        Path("mta/succ_cxt_sibling_6.c"),
        Path("mta/succ_cxt_sibling_7.c"),
        Path("mta/succ_cxt_sibling_8.c"),
        Path("mta/succ_cxt_simple_1.c"),
        Path("mta/succ_cxt_simple_2.c"),
        Path("mta/succ_cxt_simple_3.c"),
        Path("mta/succ_cxt_synthesis_1.c"),
        Path("mta/succ_cxt_thdindex_2.c"),
        Path("mta/succ_cxt_thdindex_7.c"),
        Path("mta/succ_cxt_thdindex_8_1.c"),
        Path("mta/succ_cxt_thdindex_8_3.c"),
        Path("mta/succ_cxt_thdindex_8_4.c"),
        Path("mta/tt.c"),
        Path("mta/unsound_cxt_loop_7.c"),
        Path("mta/unsound_cxt_thdindex_6.c"),

        # path_tests
        Path("path_tests/path10.c"),
        Path("path_tests/path11.c"),
        Path("path_tests/path12.c"),
        Path("path_tests/path13.c"),
        Path("path_tests/path14.c"),
        Path("path_tests/path15.c"),
        Path("path_tests/path16.c"),
        Path("path_tests/path17.c"),
        Path("path_tests/path18.c"),
        Path("path_tests/path19.c"),
        Path("path_tests/path1.c"),
        Path("path_tests/path20.c"),
        Path("path_tests/path21.c"),
        Path("path_tests/path22.c"),
        Path("path_tests/path2.c"),
        Path("path_tests/path3.c"),
        Path("path_tests/path4.c"),
        Path("path_tests/path5.c"),
        Path("path_tests/path6.c"),
        Path("path_tests/path7.c"),
        Path("path_tests/path8.c"),
        Path("path_tests/path9.c"),
    ]

    @property
    def binaries(self) -> tp.List[ProjectBinaryWrapper]:
        """Return a list of binaries generated by the project."""
        return wrap_paths_to_binaries([
            (str(file_name.with_suffix('')), BinaryType.executable)
            for file_name in self.FILE_PATHS
        ])

    def run_tests(self) -> None:
        pass

    def compile(self) -> None:
        """Compile the project."""
        source = local.path(self.source_of_primary)

        with local.cwd(source):
            for file in self.FILE_PATHS:
                arguments = [
                    f"{source}/{file}",
                    f"-I{source}",
                    "-g",  # Generate source-level debug information
                    "-S",  # Only run preprocess and compilation steps
                    "-o",
                    file.with_suffix('')
                ]
                if file.suffix == '.c':
                    bb.watch(bb.compiler.cc(self))(arguments)
                else:
                    bb.watch(bb.compiler.cxx(self))(arguments)
