name: Python CI

on:
  push:
    branches: [ vara, vara-dev ]
  pull_request:
    branches: [ vara, vara-dev ]
  merge_group:
    branches: [ vara, vara-dev ]

env:
  BB_TMP_DIR: $(pwd)/benchbuild/tmp

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: ./.github/actions/dependenciesActions

    - name: Run unittests
      run: |
        echo $BB_TMP_DIR
        mkdir -p benchbuild
        coverage run -p -m pytest varats varats-core tests
        rm -rf benchbuild

    - name: Combine Coverage
      run: |
        coverage combine -a --rcfile=.coveragerc
        coverage xml
    - name: Upload coverage report
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
