name: Docs CI

on:
  pull_request:
    branches: [ vara, vara-dev ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt install pandoc libgraphviz-dev
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Build docs
      run: |
        make html
