name: Python Release Tag Pipeline

on:
  push:
    tags:
      - 'vara-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)'

env:
  BB_TMP_DIR: $(pwd)/benchbuild/tmp
  TEST_PYPI_TOKEN: ${{ secrets.ALL_TEST_PYPI_TOKEN }}
  PYPI_TOKEN: ${{ secrets.ALL_PYPI_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

# TODO: extract into actions to re-use
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#
#    - name: Install system dependencies for CI
#      run: |
#         sudo apt-get install time git libgit2-dev ninja-build libyaml-dev libgraphviz-dev
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install wheel
#        pip install -e ./varats-core
#        pip install -e ./varats
#        pip install -r requirements.txt
#        pip install codecov
#        pip install pytest-cov
#        pip install coverage
#        pip install mypy
#    - name: Run unittests
#      run: |
#        echo $BB_TMP_DIR
#        mkdir -p benchbuild
#        coverage run -p -m pytest varats varats-core tests
#        rm -rf benchbuild
#
#    - name: Combine Coverage
#      run: |
#        coverage combine -a --rcfile=.coveragerc
#        coverage xml
#    - name: Upload coverage report
#      uses: codecov/codecov-action@v1
#      with:
#        file: ./coverage.xml
### end re-use
    - name: Create and Publish Release
      run: |
        pip install wheel tox
        tox -e release

