name: Python Release Tag Pipeline

on:
  push:
    branches: [fi-pipelinecreation]
  pull_request:
    branches: [fi-pipelinecreation]
  workflow_dispatch:
    #tags:
    #  - 'vara-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)'

env:
  BB_TMP_DIR: $(pwd)/benchbuild/tmp
  TEST_PYPI_TOKEN: ${{ secrets.ALL_TEST_PYPI_TOKEN }}
  PYPI_TOKEN: ${{ secrets.ALL_PYPI_TOKEN }}

jobs:
  tox:
    runs-on: ubuntu-20.04
      #strategy:
      # matrix:
      #  python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create and Publish Release
      run: |
        pip install wheel tox
        tox -e release

