name: Python Release Tag Pipeline

on:
  push:
    branches: [fi-pipelinecreation]
  pull_request:
    branches: [fi-pipelinecreation]
  workflow_dispatch:
    #tags:
    #  - 'vara-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)'

env:
  BB_TMP_DIR: $(pwd)/benchbuild/tmp
  TEST_PYPI_TOKEN: ${{ secrets.ALL_TEST_PYPI_TOKEN }}
  PYPI_TOKEN: ${{ secrets.ALL_PYPI_TOKEN }}

jobs:
  PublishRelease:
    runs-on: ubuntu-20.04
      #strategy:
      # matrix:
      #  python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install system dependencies for CI
      run: |
         sudo apt-get install time git libgit2-dev ninja-build libyaml-dev libgraphviz-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e ./varats-core
        pip install -e ./varats
        pip install -r requirements.txt
        pip install codecov
        pip install pytest-cov
        pip install coverage
        pip install mypy
        pip install tox
    - name: Create and Publish Release
      run: |
        echo '[distutils]
          index-servers =
            testpypi
            pypi
        
        [pypi]
          repository = https://upload.pypi.org/legacy/
          username = __token__
          password = ${{ PYPI_TOKEN }}
        
        [testpypi]
          repository = https://test.pypi.org/legacy/
          username = __token__
          password = ${{ TEST_PYPI_TOKEN }}
        ' > .pypirc
        cat .pypirc
        tox -e test-release # TODO: remove test- for production

