name: Python Release Tag Pipeline

on:
  push:
    branches: [fi-pipelinecreation]
  pull_request:
    branches: [fi-pipelinecreation]
  workflow_dispatch:
    #tags:
    #  - 'vara-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)'

env:
  BB_TMP_DIR: $(pwd)/benchbuild/tmp
  TEST_PYPI_TOKEN: ${{ secrets.ALL_TEST_PYPI_TOKEN }}
  PYPI_TOKEN: dummyToken # TODO: use ${{ secrets.ALL_PYPI_TOKEN }}

jobs:
  InstallDependencies:
    uses: .github/workflows/dependenciesTemplate.yml
  PublishRelease:
    runs-on: ubuntu-20.04
    steps:
    - name: Create and Publish Release
      run: |
        echo $BB_TMP_DIR
        tox -e test-release # TODO: remove test- for production

