name: Python Release Tag Pipeline

on:
  push:
    branches: [fi-pipelinecreation]
  pull_request:
    branches: [fi-pipelinecreation]
  workflow_dispatch:
    #tags:
    #  - 'vara-(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)'

env:
  BB_TMP_DIR: $(pwd)/benchbuild/tmp
  TEST_PYPI_TOKEN: ${{ secrets.ALL_TEST_PYPI_TOKEN }}
  PYPI_TOKEN: dummyToken # TODO: use ${{ secrets.ALL_PYPI_TOKEN }}

jobs:
  PublishRelease:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
          #    - uses: ./.github/actions/dependenciesActions
    - name: Create and Publish Release
      run: |
        echo $PYPI_TOKEN
        echo $TEST_PYPI_TOKEN
        sed -i 's/$PYPI_TOKEN/foo/' .pypirc
        sed -i 's/$TEST_PYPI_TOKEN/bar/' .pypirc
        cat .pypirc
        tox -e test-release # TODO: remove test- for production

